### ISSUE TITLE
Relax .IF expr to allow expr to be undefined

### ISSUE THREAD

**Issue by boeckmann** [boeckmann/asm6502#23]
This is desirable to allow a construct like
```
.if VICE
.else
.endif
```
Where VICE is either defined or not defined from command line.

This depends on the assembler doing proper phase error detection, otherwise this could fataly fail:
```
.if HELLO
    .byte HELLO
.else
    HELLO = 1
.endif
```

Also the implicit declaration of symbols should be suppressed when evaluating expressions within conditionals, otherwise they would show up in the symbol table, which is not desired.

**Comment by boeckmann** [comment]
This is implemented by fb0fd43. Also, `.ECHO1` is implemented, which prints its arguments on first pass. `.ECHO` does this on the second pass.

**Comment by waltje** [comment]
I do have these, and yes, they show up as ?? to remind me I used it...--Sent via my Samsung Galaxy Note® 4 4G LTE

-------- Original message --------
From: Bernd Böckmann ***@***.***> 
Date: 4/25/23  9:47 AM  (GMT-05:00) 
To: boeckmann/asm6502 ***@***.***> 
Cc: Subscribed ***@***.***> 
Subject: [boeckmann/asm6502] Relax .IF expr to allow expr to be undefined
&nbsp; (Issue #23) 


This is desirable to allow a construct like
.if VICE
.else
.endif

Where VICE is either defined or not defined from command line.
This depends on the assembler doing proper phase error detection, otherwise this could fataly fail:
.if HELLO
    .byte HELLO
.else
    HELLO = 1
.endif

Also the implicit declaration of symbols should be suppressed when evaluating expressions within conditionals, otherwise they would show up in the symbol table, which is not desired.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/boeckmann/asm6502/issues/23",
"url": "https://github.com/boeckmann/asm6502/issues/23",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by boeckmann** [comment]
Yes, perhaps better to include them in the symtbl. This is the current behaviour of my version.

**Comment by boeckmann** [comment]
Beside .IF and .IFN, which "casts" an undefined value to zero, I implemented .IFDEF and .IFNDEF which test, if the argument is defined.

**Comment by waltje** [comment]
Yep.

I did commit to my repo, so you can see what all I did.

Will implement ".ifn", although that is same as ".if !" .. :P

Fred






On Tuesday, April 25, 2023 at 03:34:33 PM EDT, Bernd Böckmann ***@***.***> wrote: 







Beside .IF and .IFN, which "casts" an undefined value to zero, I implemented .IFDEF and .IFNDEF which test, if the argument is defined.

**Comment by boeckmann** [comment]
> Yep. I did commit to my repo, so you can see what all I did. Will implement ".ifn", although that is same as ".if !" .. :P Fred 

You are right, that is redundant. Perhaps it is better to throw it out again.

**Comment by waltje** [comment]
> You are right, that is redundant. Perhaps it is better to throw it out again.

It cant hurt to leave it in. Although YOU have to watch your #lines ! :)

**Comment by boeckmann** [comment]
Well, I consider it more or less feature complete if the ifdef stuff is in :-) .IFN is four lines, I leave it in.
